sudo: false

language: php

php:
  - 7.0

before_install:
  - composer self-update
  - echo 'date.timezone = "Europe/Amsterdam"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install --optimize-autoloader --prefer-dist --no-interaction

script:
  - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run --config-file=./dev/phpcsfixer/php_cs.php
  - vendor/bin/permcheck -c dev/permcheck/permcheck.xml

cache:
  directories:
    - vendor
    - $HOME/.composer/cache/files
